[build]
# FORZAMOS A RAILWAY A USAR LA IMAGEN BASE DE PYTHON
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt" 
nixpacksBuildImage = "python:3.10" # <--- VersiÃ³n de Python

[deploy]
startCommand = "python bot.py"